<a href="https://colab.research.google.com/github/Vyshnavi153/Applied-NLP/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = dodgerred>**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [1]:
import torch
import time

# <font color = dodgerred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

# New Section

In [7]:
my_tensor = torch.zeros((5,3,))
print(my_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
my_tensor.shape

torch.Size([5, 3])

In [9]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".
my_tensor[0,2] = 10
my_tensor[2,0] = 100
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [11]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [2]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
x = x.view(6,4).T
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [4]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [5]:
x.shape

torch.Size([3, 5])

In [6]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[2]
last_row

tensor([11, 12, 13, 14, 15])

In [12]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [13]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[:3,:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [14]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[0::2,0::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = dodgerred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [15]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [16]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [17]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [18]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [19]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [20]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  x = x.float()
  mean = x.mean(axis = 0)

  # Calculate the standard deviation along each column
  std = x.std(axis = 0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x - mean)/std

  return y  # Return the normalized matrix



In [21]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [22]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

In [23]:
Z.std(axis = 0)

tensor([1., 1., 1., 1.])

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [24]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', id(A))
A.add_(5)
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B = B.add(5)
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 134064641944336
Memory address of A after in-place addition: 134064641944336
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 134064624641232
Memory address of B after out-of-place addition: 134064624578976
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**
In-Place operations demonstrated memory saving by adding 5 to the tensor without making a copy whereas Out-of-Place operations demonstrated creation of new tensors using more memory on addition of 5 to the tensor.



# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [25]:
X = torch.tensor([[11],[12],[13]])
Y = torch.tensor([[14,15,16]])
print('Original shapes:', X.shape, Y.shape)
result = X + Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[25, 26, 27],
        [26, 27, 28],
        [27, 28, 29]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**

In the above operation, since the tensors X and Y are of different shape, before addition operation, the tensor X with shape (3,1) is broadcasted internally as a tensor with shape (3,3) so as to match the tensor Y with shape (1,3). Then Y is broadcasted to have shape of (3,3) so as to match the shape of X. After broadcasting, the addition operation is done resulting in an ouput tensor with shape (3,3).

# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [26]:
M1 = torch.arange(2, 8).reshape(2,3)
print(M1)
M2 = torch.arange(3,12).reshape(3,3)
print(M2)
mat_multiplication =  torch.mm(M1,M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.arange(1,5)
print(V1)
V2 =  torch.arange(2,10,2)
dot_product =  torch.dot(V1, V2)
print(V2)
print('Dot product:', dot_product)


tensor([[2, 3, 4],
        [5, 6, 7]])
tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Matrix multiplication result: tensor([[ 60,  69,  78],
        [114, 132, 150]])
tensor([1, 2, 3, 4])
tensor([2, 4, 6, 8])
Dot product: tensor(60)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [27]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3,8)
print('T_view shape:', T_view.shape)

T_reshape =  T.reshape(4,2,3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2,1,0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**
Both reshape and view are used to change the shape of the tensor but there are differences between them.
* Reshape returns a tensor with new shape having same data as the original tensor. It can either return a view of the original tensor to avoid copying. However, in some cases it might return a copy due to non-contiguous tensors.
* View also does the same operation as reshape but it will not create a copy of the original tensor and will only work on contiguous tensor.


# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [28]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  torch.cat((C1,C2),dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1,C2),dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1,C2),dim=0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**
The difference between concatenating and stacking is that contatenation combines the input tensors along the given dimension whereas stacking combines the input tensors along the new dimension resulting in an ouput tensor with one more dimension as observed above stacked tensor with new dimension of 2.



# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [29]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n',  D[D>0.5])

second_fourth_rows =  D[[1,4],:]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  D[:3,:3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


Elements greater than 0.5:
 tensor([0.9738, 0.9139, 0.7799, 0.9268, 0.7047, 0.8066, 0.9056, 0.5459, 0.8501,
        0.9548, 0.9823, 0.6224, 0.6462, 0.8188, 0.9459, 0.9025, 0.7817, 0.9561,
        0.8808])

Second and fourth rows:
 tensor([[0.3836, 0.9268, 0.0843, 0.7047, 0.8066, 0.9056],
        [0.6462, 0.4828, 0.2659, 0.8188, 0.9459, 0.1889]])

Top-left 3x3 block:
  tensor([[0.9738, 0.0041, 0.0823],
        [0.3836, 0.9268, 0.0843],
        [0.4133, 0.2602, 0.5459]])


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [30]:
import math
G = torch.arange(0, math.pi+math.pi/4, math.pi/4)
print('G:', G)
print('Sine of G:', torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:',  torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:',  torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
Sine of G: tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  8.7423e-08])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570,  1.1447])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507, 23.1407])


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [31]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  H.sum())
print('Shape after Sum of H:',  H.sum().shape,  end = "\n\n")

print('Sum of H along dimension 0:',  H.sum(axis=0))
print('Shape after sum of H along dimension 0:',  H.sum(axis=0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', H.sum(axis=1))
print('Shape after sum of H along dimension 1:',  H.sum(axis=1).shape)


H: tensor([[0.0247, 0.3586],
        [0.9049, 0.5777],
        [0.9424, 0.4194]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.2277)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.8720, 1.3557])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([0.3834, 1.4826, 1.3617])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**
* Calculating sum of all the elements by default gave a scalar value by reducing the tensor along all its axes.
* Calculating sum along axis = 0 i.e. along the rows for a tensor of size (3,2) has resulted in a 1-dimensional tensor of shape (1,2) representing the sum of rows of the tensor.
* Calculating the sum along axis = 1 i.e. along the columns of the tensor of sie (3,2) resulted in a 1-dimensional tensor of shape (1,3) representing the sum of columns of the tensor.



# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [32]:
# Solution for Q16
I =  torch.tensor([1.0,2.0,3.0], dtype = torch.float)
print('I:', I)
I_int =  I.type(dtype=torch.int32)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**
* During intialization of tensors to ensure that the tensors created are of specific data type.
* While performing operations, it is important to be cautious about the data types to ensure precision in computing for more accurate results.


# <font color = 'dodgerred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [33]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024,1024)
B = torch.randn(1024,1024)

In [34]:
A.device

device(type='cpu')

In [35]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.038729190826416016 seconds


In [36]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(B.shape[1]):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 1.9541082382202148 seconds


In [37]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j] = torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 28.88134741783142 seconds


# <font color = 'dodgerred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [38]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [39]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [40]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.10108137130737305 seconds


In [41]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(B.shape[1]):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.09204864501953125 seconds


In [42]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j] = torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 44.3972487449646 seconds
